---

- hosts: all
  become: true
  tasks:

    - name: update apt cache(hitt me apt jalparant name dennesa kide huntan me kai install karit naisa hitt)
      apt:
        update_cache: yes


    - name: install apache package(install karle matra name devn install karunche)hitt barelle run kartan tasks under yanta bag
      apt:
        name: apache2
        state: latest
